import { hashString, seededRandom } from "@/lib/utils"

export interface Wijk {
  name: string
  slug: string
}

export interface City {
  id: number
  name: string
  slug: string
  province: string
  inhabitants: number
  priority: 1 | 2 | 3
  isLive: boolean
  wijken: Wijk[]
  image?: string
  imageAlt?: string
}

// Generate consistent fake statistics for cities
export function generateCityStats(city: City) {
  const baseTraders = Math.floor(city.inhabitants / 800)
  const variance = (hashString(city.slug) % 20) - 10 // -10% tot +10%
  const tradersActive = Math.floor(baseTraders + (baseTraders * variance) / 100)

  return {
    tradersActive,
    accountsOpened: Math.floor(tradersActive * 0.4),
    avgAccountSize: 25000 + seededRandom(city.slug + "-account", 0, 25000),
    popularFirm: city.priority === 1 ? "FTMO" : "Apex",
    successRate: 12 + seededRandom(city.slug + "-success", 0, 8), // 12-20%
    avgMonthlyProfit: 2500 + seededRandom(city.slug + "-profit", 0, 2500),
  }
}

// Generate wijk stats
export function generateWijkStats(wijk: Wijk, city: City) {
  const cityStats = generateCityStats(city)
  const wijkShare = seededRandom(wijk.slug, 5, 20) // 5-20% of city traders

  return {
    tradersActive: Math.floor((cityStats.tradersActive * wijkShare) / 100),
    popularFirm: seededRandom(wijk.slug + "-firm", 0, 10) > 5 ? "FTMO" : "Apex",
  }
}

export const cities: City[] = [
  // Priority 1 - Top 10
  {
    id: 1,
    name: "Amsterdam",
    slug: "amsterdam",
    province: "Noord-Holland",
    inhabitants: 921000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Oost", slug: "oost" },
      { name: "Noord", slug: "noord" },
      { name: "Nieuw-West", slug: "nieuw-west" },
      { name: "Zuidoost", slug: "zuidoost" },
      { name: "De Pijp", slug: "de-pijp" },
      { name: "Jordaan", slug: "jordaan" },
      { name: "IJburg", slug: "ijburg" },
    ],
  },
  {
    id: 2,
    name: "Rotterdam",
    slug: "rotterdam",
    province: "Zuid-Holland",
    inhabitants: 656000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Kralingen", slug: "kralingen" },
      { name: "Hillegersberg", slug: "hillegersberg" },
      { name: "Delfshaven", slug: "delfshaven" },
      { name: "Noord", slug: "noord" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Feijenoord", slug: "feijenoord" },
      { name: "Charlois", slug: "charlois" },
      { name: "Hoogvliet", slug: "hoogvliet" },
    ],
  },
  {
    id: 3,
    name: "Den Haag",
    slug: "den-haag",
    province: "Zuid-Holland",
    inhabitants: 552000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Scheveningen", slug: "scheveningen" },
      { name: "Loosduinen", slug: "loosduinen" },
      { name: "Laak", slug: "laak" },
      { name: "Haagse Hout", slug: "haagse-hout" },
      { name: "Leidschenveen", slug: "leidschenveen" },
      { name: "Segbroek", slug: "segbroek" },
      { name: "Escamp", slug: "escamp" },
      { name: "Binckhorst", slug: "binckhorst" },
      { name: "Ypenburg", slug: "ypenburg" },
    ],
  },
  {
    id: 4,
    name: "Utrecht",
    slug: "utrecht",
    province: "Utrecht",
    inhabitants: 361000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Oost", slug: "oost" },
      { name: "West", slug: "west" },
      { name: "Zuid", slug: "zuid" },
      { name: "Noordwest", slug: "noordwest" },
      { name: "Leidsche Rijn", slug: "leidsche-rijn" },
      { name: "Vleuten", slug: "vleuten" },
      { name: "Overvecht", slug: "overvecht" },
      { name: "Lunetten", slug: "lunetten" },
      { name: "Hoograven", slug: "hoograven" },
    ],
  },
  {
    id: 5,
    name: "Eindhoven",
    slug: "eindhoven",
    province: "Noord-Brabant",
    inhabitants: 238000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Strijp", slug: "strijp" },
      { name: "Woensel", slug: "woensel" },
      { name: "Gestel", slug: "gestel" },
      { name: "Stratum", slug: "stratum" },
      { name: "Tongelre", slug: "tongelre" },
      { name: "Acht", slug: "acht" },
      { name: "Meerhoven", slug: "meerhoven" },
      { name: "Blixembosch", slug: "blixembosch" },
      { name: "Gennep", slug: "gennep" },
    ],
  },
  {
    id: 6,
    name: "Groningen",
    slug: "groningen",
    province: "Groningen",
    inhabitants: 234000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Paddepoel", slug: "paddepoel" },
      { name: "Vinkhuizen", slug: "vinkhuizen" },
      { name: "Helpman", slug: "helpman" },
      { name: "Oosterpark", slug: "oosterpark" },
      { name: "Selwerd", slug: "selwerd" },
      { name: "Hoogkerk", slug: "hoogkerk" },
      { name: "Haren", slug: "haren" },
      { name: "Beijum", slug: "beijum" },
      { name: "Lewenborg", slug: "lewenborg" },
    ],
  },
  {
    id: 7,
    name: "Tilburg",
    slug: "tilburg",
    province: "Noord-Brabant",
    inhabitants: 224000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Reeshof", slug: "reeshof" },
      { name: "Berkel-Enschot", slug: "berkel-enschot" },
      { name: "Udenhout", slug: "udenhout" },
      { name: "Korvel", slug: "korvel" },
      { name: "Goirle", slug: "goirle" },
    ],
  },
  {
    id: 8,
    name: "Almere",
    slug: "almere",
    province: "Flevoland",
    inhabitants: 218000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Almere Stad", slug: "almere-stad" },
      { name: "Haven", slug: "haven" },
      { name: "Buiten", slug: "buiten" },
      { name: "Poort", slug: "poort" },
      { name: "Hout", slug: "hout" },
      { name: "Pampus", slug: "pampus" },
      { name: "Centrum", slug: "centrum" },
      { name: "Muziekwijk", slug: "muziekwijk" },
      { name: "Literatuurwijk", slug: "literatuurwijk" },
      { name: "Stedenwijk", slug: "stedenwijk" },
    ],
  },
  {
    id: 9,
    name: "Breda",
    slug: "breda",
    province: "Noord-Brabant",
    inhabitants: 185000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Princenhage", slug: "princenhage" },
      { name: "Ginneken", slug: "ginneken" },
      { name: "Bavel", slug: "bavel" },
      { name: "Teteringen", slug: "teteringen" },
      { name: "Ulvenhout", slug: "ulvenhout" },
    ],
  },
  {
    id: 10,
    name: "Nijmegen",
    slug: "nijmegen",
    province: "Gelderland",
    inhabitants: 179000,
    priority: 1,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Oost", slug: "oost" },
      { name: "West", slug: "west" },
      { name: "Noord", slug: "noord" },
      { name: "Zuid", slug: "zuid" },
      { name: "Dukenburg", slug: "dukenburg" },
      { name: "Lindenholt", slug: "lindenholt" },
      { name: "Hatert", slug: "hatert" },
      { name: "Neerbosch", slug: "neerbosch" },
      { name: "Lent", slug: "lent" },
    ],
  },

  // Priority 2 - 11-25
  {
    id: 11,
    name: "Apeldoorn",
    slug: "apeldoorn",
    province: "Gelderland",
    inhabitants: 165000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "De Maten", slug: "de-maten" },
      { name: "Osseveld", slug: "osseveld" },
      { name: "Zevenhuizen", slug: "zevenhuizen" },
      { name: "Orden", slug: "orden" },
      { name: "Berg en Bos", slug: "berg-en-bos" },
    ],
  },
  {
    id: 12,
    name: "Haarlem",
    slug: "haarlem",
    province: "Noord-Holland",
    inhabitants: 162000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Schalkwijk", slug: "schalkwijk" },
      { name: "Zuidwest", slug: "zuidwest" },
      { name: "Heemstede", slug: "heemstede" },
      { name: "Spaarndam", slug: "spaarndam" },
      { name: "Overveen", slug: "overveen" },
      { name: "Santpoort", slug: "santpoort" },
      { name: "Bloemendaal", slug: "bloemendaal" },
    ],
  },
  {
    id: 13,
    name: "Arnhem",
    slug: "arnhem",
    province: "Gelderland",
    inhabitants: 162000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Presikhaaf", slug: "presikhaaf" },
      { name: "Malburgen", slug: "malburgen" },
      { name: "Kronenburg", slug: "kronenburg" },
      { name: "Velp", slug: "velp" },
      { name: "Schuytgraaf", slug: "schuytgraaf" },
    ],
  },
  {
    id: 14,
    name: "Enschede",
    slug: "enschede",
    province: "Overijssel",
    inhabitants: 160000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Roombeek", slug: "roombeek" },
      { name: "Glanerbrug", slug: "glanerbrug" },
      { name: "Lonneker", slug: "lonneker" },
      { name: "Deppenbroek", slug: "deppenbroek" },
      { name: "Wesselerbrink", slug: "wesselerbrink" },
    ],
  },
  {
    id: 15,
    name: "Amersfoort",
    slug: "amersfoort",
    province: "Utrecht",
    inhabitants: 159000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Vathorst", slug: "vathorst" },
      { name: "Nieuwland", slug: "nieuwland" },
      { name: "Kattenbroek", slug: "kattenbroek" },
      { name: "Schothorst", slug: "schothorst" },
      { name: "Soesterkwartier", slug: "soesterkwartier" },
    ],
  },
  {
    id: 16,
    name: "Zaanstad",
    slug: "zaanstad",
    province: "Noord-Holland",
    inhabitants: 157000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Zaandam", slug: "zaandam" },
      { name: "Wormerveer", slug: "wormerveer" },
      { name: "Krommenie", slug: "krommenie" },
      { name: "Assendelft", slug: "assendelft" },
      { name: "Koog aan de Zaan", slug: "koog-aan-de-zaan" },
      { name: "Zaandijk", slug: "zaandijk" },
      { name: "Westzaan", slug: "westzaan" },
      { name: "Oostzaan", slug: "oostzaan" },
      { name: "Westknollendam", slug: "westknollendam" },
      { name: "Kogerveld", slug: "kogerveld" },
    ],
  },
  {
    id: 17,
    name: "Haarlemmermeer",
    slug: "haarlemmermeer",
    province: "Noord-Holland",
    inhabitants: 156000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Hoofddorp", slug: "hoofddorp" },
      { name: "Nieuw-Vennep", slug: "nieuw-vennep" },
      { name: "Badhoevedorp", slug: "badhoevedorp" },
      { name: "Zwanenburg", slug: "zwanenburg" },
      { name: "Abbenes", slug: "abbenes" },
      { name: "Beinsdorp", slug: "beinsdorp" },
      { name: "Cruquius", slug: "cruquius" },
      { name: "Rijsenhout", slug: "rijsenhout" },
      { name: "Lisserbroek", slug: "lisserbroek" },
      { name: "Zwaanshoek", slug: "zwaanshoek" },
    ],
  },
  {
    id: 18,
    name: "'s-Hertogenbosch",
    slug: "s-hertogenbosch",
    province: "Noord-Brabant",
    inhabitants: 155000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Rosmalen", slug: "rosmalen" },
      { name: "Maaspoort", slug: "maaspoort" },
      { name: "De Groote Wielen", slug: "de-groote-wielen" },
      { name: "Empel", slug: "empel" },
      { name: "Engelen", slug: "engelen" },
    ],
  },
  {
    id: 19,
    name: "Zwolle",
    slug: "zwolle",
    province: "Overijssel",
    inhabitants: 131000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Stadshagen", slug: "stadshagen" },
      { name: "Assendorp", slug: "assendorp" },
      { name: "Dieze", slug: "dieze" },
      { name: "Holtenbroek", slug: "holtenbroek" },
      { name: "Berkum", slug: "berkum" },
    ],
  },
  {
    id: 20,
    name: "Zoetermeer",
    slug: "zoetermeer",
    province: "Zuid-Holland",
    inhabitants: 125000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Meerzicht", slug: "meerzicht" },
      { name: "Buytenwegh", slug: "buytenwegh" },
      { name: "Seghwaert", slug: "seghwaert" },
      { name: "Palenstein", slug: "palenstein" },
      { name: "Rokkeveen", slug: "rokkeveen" },
      { name: "Stadshart", slug: "stadshart" },
      { name: "Oosterheem", slug: "oosterheem" },
      { name: "De Leyens", slug: "de-leyens" },
      { name: "Dorp", slug: "dorp" },
    ],
  },
  {
    id: 21,
    name: "Leiden",
    slug: "leiden",
    province: "Zuid-Holland",
    inhabitants: 124000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Stevenshof", slug: "stevenshof" },
      { name: "Merenwijk", slug: "merenwijk" },
      { name: "Professorenwijk", slug: "professorenwijk" },
      { name: "Morsstraat", slug: "morsstraat" },
      { name: "Boskoop", slug: "boskoop" },
    ],
  },
  {
    id: 22,
    name: "Leeuwarden",
    slug: "leeuwarden",
    province: "Friesland",
    inhabitants: 124000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Camminghaburen", slug: "camminghaburen" },
      { name: "Bilgaard", slug: "bilgaard" },
      { name: "Huizum", slug: "huizum" },
      { name: "Aldlân", slug: "aldlan" },
      { name: "Goutum", slug: "goutum" },
    ],
  },
  {
    id: 23,
    name: "Maastricht",
    slug: "maastricht",
    province: "Limburg",
    inhabitants: 121000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Wyck", slug: "wyck" },
      { name: "Céramique", slug: "ceramique" },
      { name: "Randwyck", slug: "randwyck" },
      { name: "Wolder", slug: "wolder" },
      { name: "Borgharen", slug: "borgharen" },
    ],
  },
  {
    id: 24,
    name: "Dordrecht",
    slug: "dordrecht",
    province: "Zuid-Holland",
    inhabitants: 119000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Stadspolders", slug: "stadspolders" },
      { name: "Sterrenburg", slug: "sterrenburg" },
      { name: "Dubbeldam", slug: "dubbeldam" },
      { name: "Wielwijk", slug: "wielwijk" },
      { name: "Krispijn", slug: "krispijn" },
    ],
  },
  {
    id: 25,
    name: "Ede",
    slug: "ede",
    province: "Gelderland",
    inhabitants: 119000,
    priority: 2,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
      { name: "Veldhuizen", slug: "veldhuizen" },
      { name: "Kernhem", slug: "kernhem" },
      { name: "Lunteren", slug: "lunteren" },
      { name: "Bennekom", slug: "bennekom" },
      { name: "Otterlo", slug: "otterlo" },
    ],
  },

  // Priority 3 - 26-50
  {
    id: 26,
    name: "Alphen aan den Rijn",
    slug: "alphen-aan-den-rijn",
    province: "Zuid-Holland",
    inhabitants: 113000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 27,
    name: "Westland",
    slug: "westland",
    province: "Zuid-Holland",
    inhabitants: 111000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Naaldwijk", slug: "naaldwijk" },
      { name: "Monster", slug: "monster" },
      { name: "'s-Gravenzande", slug: "s-gravenzande" },
      { name: "Wateringen", slug: "wateringen" },
      { name: "De Lier", slug: "de-lier" },
    ],
  },
  {
    id: 28,
    name: "Alkmaar",
    slug: "alkmaar",
    province: "Noord-Holland",
    inhabitants: 110000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 29,
    name: "Emmen",
    slug: "emmen",
    province: "Drenthe",
    inhabitants: 107000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 30,
    name: "Delft",
    slug: "delft",
    province: "Zuid-Holland",
    inhabitants: 104000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 31,
    name: "Venlo",
    slug: "venlo",
    province: "Limburg",
    inhabitants: 101000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 32,
    name: "Deventer",
    slug: "deventer",
    province: "Overijssel",
    inhabitants: 101000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 33,
    name: "Helmond",
    slug: "helmond",
    province: "Noord-Brabant",
    inhabitants: 93000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 34,
    name: "Hilversum",
    slug: "hilversum",
    province: "Noord-Holland",
    inhabitants: 92000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 35,
    name: "Oss",
    slug: "oss",
    province: "Noord-Brabant",
    inhabitants: 92000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 36,
    name: "Sittard-Geleen",
    slug: "sittard-geleen",
    province: "Limburg",
    inhabitants: 92000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Sittard", slug: "sittard" },
      { name: "Geleen", slug: "geleen" },
      { name: "Born", slug: "born" },
      { name: "Munstergeleen", slug: "munstergeleen" },
      { name: "Limbricht", slug: "limbricht" },
    ],
  },
  {
    id: 37,
    name: "Amstelveen",
    slug: "amstelveen",
    province: "Noord-Holland",
    inhabitants: 91000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 38,
    name: "Heerlen",
    slug: "heerlen",
    province: "Limburg",
    inhabitants: 87000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 39,
    name: "Purmerend",
    slug: "purmerend",
    province: "Noord-Holland",
    inhabitants: 81000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 40,
    name: "Lelystad",
    slug: "lelystad",
    province: "Flevoland",
    inhabitants: 81000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 41,
    name: "Schiedam",
    slug: "schiedam",
    province: "Zuid-Holland",
    inhabitants: 79000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 42,
    name: "Roosendaal",
    slug: "roosendaal",
    province: "Noord-Brabant",
    inhabitants: 77000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 43,
    name: "Hoorn",
    slug: "hoorn",
    province: "Noord-Holland",
    inhabitants: 74000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 44,
    name: "Gouda",
    slug: "gouda",
    province: "Zuid-Holland",
    inhabitants: 74000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 45,
    name: "Spijkenisse",
    slug: "spijkenisse",
    province: "Zuid-Holland",
    inhabitants: 72000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 46,
    name: "Vlaardingen",
    slug: "vlaardingen",
    province: "Zuid-Holland",
    inhabitants: 72000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 47,
    name: "Veenendaal",
    slug: "veenendaal",
    province: "Utrecht",
    inhabitants: 68000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 48,
    name: "Bergen op Zoom",
    slug: "bergen-op-zoom",
    province: "Noord-Brabant",
    inhabitants: 67000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 49,
    name: "Capelle aan den IJssel",
    slug: "capelle-aan-den-ijssel",
    province: "Zuid-Holland",
    inhabitants: 67000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Centrum", slug: "centrum" },
      { name: "Noord", slug: "noord" },
      { name: "Oost", slug: "oost" },
      { name: "Zuid", slug: "zuid" },
      { name: "West", slug: "west" },
    ],
  },
  {
    id: 50,
    name: "Katwijk",
    slug: "katwijk",
    province: "Zuid-Holland",
    inhabitants: 66000,
    priority: 3,
    isLive: true,
    wijken: [
      { name: "Katwijk aan Zee", slug: "katwijk-aan-zee" },
      { name: "Katwijk aan den Rijn", slug: "katwijk-aan-den-rijn" },
      { name: "Rijnsburg", slug: "rijnsburg" },
      { name: "Valkenburg", slug: "valkenburg" },
      { name: "Hoornes", slug: "hoornes" },
    ],
  },
]

// Helper functions
export function getCityBySlug(slug: string): City | undefined {
  return cities.find((city) => city.slug === slug)
}

export function getCitiesByPriority(priority: 1 | 2 | 3): City[] {
  return cities.filter((city) => city.priority === priority && city.isLive)
}

export function getTopCities(count: number = 10): City[] {
  return cities
    .filter((city) => city.isLive)
    .sort((a, b) => a.priority - b.priority || b.inhabitants - a.inhabitants)
    .slice(0, count)
}

export function getAllCities(): City[] {
  return cities.filter((city) => city.isLive)
}

export function getWijkBySlug(citySlug: string, wijkSlug: string): Wijk | undefined {
  const city = getCityBySlug(citySlug)
  return city?.wijken.find((wijk) => wijk.slug === wijkSlug)
}
